version: '3'

services:

  terraform:
    image: hashicorp/terraform:1.3.9
    depends_on: [ localstack ]
    working_dir: /app
    environment:
      TF_LOG: ${TF_LOG:-info}
    volumes:
      - '.:/app'

  terraform-docs:
    image: quay.io/terraform-docs/terraform-docs:0.16.0
    working_dir: /app
    volumes:
      - '.:/app'

  asciidoctor:
    image: asciidoctor/docker-asciidoctor:1.30.0
    entrypoint: asciidoctor
    working_dir: /app
    volumes:
      - '.:/app'

  localstack:
    image: localstack/localstack:1.0.4
    environment:
      DEBUG:               '1'
      TEST_AWS_ACCOUNT_ID: '000000000000'

