= Terraform AWS Network Security
:description: A helper module to make managing rules for Security Groups and \
NACLs less painful.
:toc:
:toc-placement!:

ifndef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[]
:rendered-site: https://tzrlk.github.io/terraform-aws-network-security/
{rendered-site}[Rendered Docs]
endif::[]

{description}

This module is only a one-stop-shop for network security rule generation. It
may stray into the realm of VPC setup, but only the parts directly relating to
network security.

toc::[]

== Usage
This module requires you to assign every port range, CIDR block, and Security
Group a name. Then you provide a set of mappings between source and destination
groups, listing the port ranges that are open. All of this is done by referencing
the names you gave them earlier. Finally, the module flattens this config and
builds the network security rules from it.

=== Example

ifdef::env-github[]
Examples are present in the `tests/` folder, and one is detailed in the
{rendered-site}[rendered version of the docs].
endif::[]
ifndef::env-github[]

The following example hopefully shows how easy setting up the rules becomes
when you're focusing on the intent.

[source,terraform]
----
include::tests/example/setup.tf[]
----

== Terraform Docs
include::terraform.adoc[]

endif::[]

== Potential Future Work

* Security Group creation.
* Output graphviz of rules.

