= Terraform AWS Network Security
:description: A helper module to make managing rules for Security Groups and \
NACLs less painful.
:toc:
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

{description}

This module is only a one-stop-shop for network security rule generation. It
may stray into the realm of VPC setup, but only the parts directly relating to
network security.

toc::[]

== Usage
This module requires you to assign every port range, CIDR block, and Security
Group a name. Then you provide a set of mappings between source and destination
groups, listing the port ranges that are open. All of this is done by referencing
the names you gave them earlier. Finally, the module flattens this config and
builds the network security rules from it.

=== Example
The following example hopefully shows how easy setting up the rules becomes
when you're focusing on the intent. 

:mod_ver: > 0
[source,terraform]
----
module "NetSec" {
	source  = "tzrlk/network-security/aws"
	version = "{mod_ver}"

	SecurityGroupIds = {
		Albs = "sg-aaaaaaaaaaaaaaaa" # Public-facing load balancers.
		Apps = "sg-bbbbbbbbbbbbbbbb" # Protected apps
		Data = "sg-cccccccccccccccc" # Private database
	}

	CidrBlocks = {
		Anywhere = "0.0.0.0/0" <1>
		AdminVm  = "123.123.123.123/32" <2>
	}

	PortRanges = {
		Dns    = { Proto = "udp", Min = 53,   Max = 53 }
		Http   = { Proto = "tcp", Min = 80,   Max = 80 }
		Https  = { Proto = "tcp", Min = 443,  Max = 443 }
		Https2 = { Proto = "tcp", Min = 8443, Max = 8443 }
		Jdbc   = { Proto = "tcp", Min = 5432, Max = 5432 }
		Ssh    = { Proto = "tcp", Min = 22,   Max = 22 }
	}

	Rules = {
		Anywhere = {
			Albs = [ "Http", "Https" ] <3>
		}
		Albs = {
			Apps = [ "Https2" ] <4>
		}
		Apps = {
			Anywhere = [ "Https" ] <5>
			Apps     = [ "Https2", "Dns" ] <6>
			Data     = [ "Jdbc", "Dns" ] <7>
		}
		AdminVm = {
			Apps = [ "Https2", "Ssh" ] <8>
			Data = [ "Https",  "Ssh", "Jdbc" ] <9>
		}
        Data = {} <10>
	}
	
}

# Output all the security rules generated by the module and attached to the
# "Alb" security group.
Output "NetSecAlbRules" {
	value = [ for Rule in module.NetSec.GroupRules["Albs"] : Rule.id ]
}
----
<1> A.k.a The internet. Always included, but can be overridden.
<2> An extremely bad example, don't actually do this.
<3> The internet can access albs via https or http (which redirects to https).
<4> Albs can access apps via unreserved https.
<5> Apps can access the internet via https.
<6> Apps can access each other via https and dns.
<7> Apps can access the database via JDBC.
<8> The admin VM can access apps via unreserved https or ssh.
<9> The admin VM can access the database by https, ssh, and jdbc.
<10> Databases don't initiate any connections.

ifeval::["{mod_ver}" != "> 0"]
== Terraform Docs
include::terraform.adoc[]
endif::[]

== Potential Future Work

* Security Group creation.
* Support for NACLs.
* Subnet creation? (Probably a different module)
* Proto should have option of both, and default to tcp.
* Max port should default to min.
* Output graphviz of rules.

