name: Push Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:

  docs:
    runs-on:     ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: terraform
        run:  make docs

      - name: asciidoc
        run:  make site

      - name: site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages
